_VPATH	+=:$(ROOT)/i2c/legacy

PROCOBJ	+= idle_i2c1_lib_legacy.o
PROCOBJ	+= idle_i2c2_lib_legacy.o
PROCOBJ	+= master_gets_i2c1_lib_legacy.o
PROCOBJ	+= master_gets_i2c2_lib_legacy.o
PROCOBJ	+= master_puts_i2c1_lib_legacy.o
PROCOBJ	+= master_puts_i2c2_lib_legacy.o
PROCOBJ	+= master_read_i2c1_lib_legacy.o
PROCOBJ	+= master_read_i2c2_lib_legacy.o
PROCOBJ	+= master_write_i2c1_lib_legacy.o
PROCOBJ	+= master_write_i2c2_lib_legacy.o
PROCOBJ	+= slave_gets_i2c1_lib_legacy.o
PROCOBJ	+= slave_gets_i2c2_lib_legacy.o
PROCOBJ	+= slave_puts_i2c1_lib_legacy.o
PROCOBJ	+= slave_puts_i2c2_lib_legacy.o
PROCOBJ	+= slave_read_i2c1_lib_legacy.o
PROCOBJ	+= slave_read_i2c2_lib_legacy.o
PROCOBJ	+= slave_write_i2c1_lib_legacy.o
PROCOBJ	+= slave_write_i2c2_lib_legacy.o

